### ISSUE TITLE
Internal Server Error with the demo provided. 

### ISSUE THREAD

**Issue by archienorman11** [nathancahill/Flask-Edits#3]
When I run the demo provided:

```
{% editable 'Section name' %}
Python is a programming language that lets you work quickly and integrate systems more effectively.
{% end editable %
```

I see an internal server error. Any thoughts? 

Removing the editable section above loads the page correctly. (I am using a Hello World example as test this out.)

Error:

```
File "/anaconda/lib/python3.5/site-packages/flask_edits/editable.py", line 18, in parse
parser.stream.next()
AttributeError: 'TokenStream' object has no attribute 'next'
```

Thanks,

**Comment by vladimirmyshkovski** [comment]
Hi!
Change `.next()` to `__next__()` (python 3.5)
then `iteritems` to `items`

You will encounter and other problems.
If it does not solve - please contact me
